name = "Spade"
version = "0.0.1"
authors = ["Daria Mukhina <me@dasha.fyi>"]
description = "Spade support."
repository = "https://github.com/syrkatheprincess/zed-spade"
id = "spade"
schema_version = 1

[grammars.spade]
repository = "https://gitlab.com/spade-lang/tree-sitter-spade/"
commit = "f4f62fcb2340d744f6df48de22b5f239beecdab5"

[language_servers.spade-language-server]
name = "spade-language-server"
languages = ["Spade"]
